# Generated by Django 6.0.1 on 2026-01-27 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo_sigla', models.CharField(help_text='ID único interno (ej: MAT-PRI-2025)', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'asignatura',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_mensualidad', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'concepto_pago',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del grupo si aplica', max_length=120, null=True)),
                ('es_grupal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversacion',
            },
        ),
        migrations.CreateModel(
            name='EscalaCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('es_literal', models.BooleanField(default=False)),
                ('nota_minima', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=20, max_digits=4)),
                ('nota_aprobatoria', models.DecimalField(decimal_places=2, default=10.5, max_digits=4)),
            ],
            options={
                'db_table': 'escala_calificacion',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden correlativo para certificados (1, 2, 3...)')),
            ],
            options={
                'db_table': 'grado',
                'ordering': ['nivel_tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('codigo_modular', models.CharField(help_text='Código identificador ante el MINEDU', max_length=20, unique=True)),
                ('codigo_local', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('ubigeo', models.CharField(blank=True, help_text='Código de ubicación geográfica', max_length=6, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ie/logos/')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'db_table': 'institucion_educativa',
            },
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio_aprobacion', models.PositiveSmallIntegerField()),
                ('es_vigente', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'malla_curricular',
            },
        ),
        migrations.CreateModel(
            name='NivelCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nivel del Sistema Educativo',
                'db_table': 'nivel_catalogo',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('peso_porcentual', models.PositiveSmallIntegerField(default=25)),
            ],
            options={
                'db_table': 'tipo_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleMalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveSmallIntegerField(default=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.asignatura')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.grado')),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='IEAPI.mallacurricular')),
            ],
            options={
                'db_table': 'detalle_malla',
                'unique_together': {('malla', 'grado', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.detallemalla')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_programada', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='IEAPI.curso')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.escalacalificacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.tipoevaluacion')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.AddField(
            model_name='mallacurricular',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.nivelcatalogo'),
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados', to='IEAPI.nivelcatalogo'),
        ),
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='DNI, Pasaporte o Carnet de Extranjería', max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_persona',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='IEAPI.conversacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enviados', to='IEAPI.perfilpersona')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='leidos', to='IEAPI.perfilpersona')),
            ],
            options={
                'db_table': 'mensaje',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado/Saliente'), ('trasladado', 'Traslado Interno'), ('reingresante', 'Reingresante')], default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Razón de cambio de sección o retiro')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='IEAPI.perfilpersona')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='participantes',
            field=models.ManyToManyField(related_name='conversaciones', to='IEAPI.perfilpersona'),
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_periodo_actual', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='IEAPI.institucioneducativa')),
            ],
            options={
                'db_table': 'periodo_lectivo',
                'ordering': ['-anio'],
                'unique_together': {('institucion', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.periodolectivo'),
        ),
        migrations.CreateModel(
            name='PersonalPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_departamento', models.CharField(blank=True, help_text='Ej: Limpieza, Administración, Matemática', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_titular', models.BooleanField(default=True)),
                ('observaciones_gestion', models.TextField(blank=True, help_text='Motivo de cambio o rotación')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.periodolectivo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.perfilpersona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.rol')),
            ],
            options={
                'db_table': 'personal_periodo',
            },
        ),
        migrations.CreateModel(
            name='DebateTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Contexto o disparador del debate')),
                ('cerrado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='IEAPI.curso')),
                ('creador_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='IEAPI.matricula')),
                ('creador_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='IEAPI.personalperiodo')),
            ],
            options={
                'db_table': 'debate_tema',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DebatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='IEAPI.debatepost')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='IEAPI.debatetema')),
                ('autor_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='IEAPI.matricula')),
                ('autor_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='IEAPI.personalperiodo')),
            ],
            options={
                'db_table': 'debate_post',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_responsable',
            field=models.ForeignKey(limit_choices_to={'rol__nombre__icontains': 'Profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_dictados', to='IEAPI.personalperiodo'),
        ),
        migrations.CreateModel(
            name='AsistenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('T', 'Tardanza'), ('J', 'Justificada')], max_length=1)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='IEAPI.personalperiodo')),
            ],
            options={
                'db_table': 'asistencia_personal',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(default='Única', max_length=20)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='mañana', max_length=10)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Híbrido')], default='presencial', max_length=15)),
                ('vacantes', models.PositiveSmallIntegerField(default=30)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.grado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='IEAPI.periodolectivo')),
            ],
            options={
                'db_table': 'seccion',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='IEAPI.seccion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='IEAPI.seccion'),
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Cuerpo del mensaje o comunicado')),
                ('fijado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.periodolectivo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.personalperiodo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='IEAPI.seccion')),
            ],
            options={
                'db_table': 'anuncio',
                'ordering': ['-fijado', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_periodo', models.CharField(help_text="Ej: 'Bimestre 1', 'Ciclo 2026-I'", max_length=50)),
                ('nombre', models.CharField(max_length=120)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso (0.01 - 100.00)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='IEAPI.curso')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='IEAPI.tipoevaluacion')),
            ],
            options={
                'db_table': 'componente_evaluacion',
                'ordering': ['curso', 'denominacion_periodo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('leyenda', models.CharField(max_length=100)),
                ('valor_numerico', models.DecimalField(decimal_places=2, help_text='Equivalencia para promedios', max_digits=4)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='IEAPI.escalacalificacion')),
            ],
            options={
                'db_table': 'valor_escala',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observado', models.BooleanField(default=False)),
                ('comentario_docente', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='IEAPI.evaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='IEAPI.matricula')),
                ('valor_literal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='IEAPI.valorescala')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('T', 'Tardanza'), ('J', 'Justificada')], max_length=1)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='IEAPI.matricula')),
            ],
            options={
                'db_table': 'asistencia_alumno',
                'unique_together': {('matricula', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='InstitucionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_configurados', to='IEAPI.institucioneducativa')),
                ('nivel_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.nivelcatalogo')),
            ],
            options={
                'db_table': 'institucion_nivel',
                'unique_together': {('institucion', 'nivel_tipo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together={('nivel_tipo', 'nombre')},
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEAPI.institucioneducativa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEAPI.perfilpersona')),
            ],
            options={
                'db_table': 'asignacion_rol',
                'unique_together': {('persona', 'institucion', 'rol_nombre')},
            },
        ),
        migrations.CreateModel(
            name='ObligacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esta_pagado', models.BooleanField(default=False)),
                ('fecha_pago_realizado', models.DateTimeField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.conceptopago')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='IEAPI.perfilpersona')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IEAPI.periodolectivo')),
            ],
            options={
                'db_table': 'obligacion_pago',
                'unique_together': {('persona', 'periodo', 'concepto')},
            },
        ),
        migrations.AddIndex(
            model_name='debatetema',
            index=models.Index(fields=['curso'], name='idx_debate_curso'),
        ),
        migrations.AddIndex(
            model_name='debatetema',
            index=models.Index(fields=['cerrado', 'creado_en'], name='idx_debate_status'),
        ),
        migrations.AddIndex(
            model_name='debatepost',
            index=models.Index(fields=['tema', 'creado_en'], name='idx_post_tema_time'),
        ),
        migrations.AddIndex(
            model_name='debatepost',
            index=models.Index(fields=['parent'], name='idx_post_parent_hilo'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciapersonal',
            unique_together={('personal', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('periodo', 'grado', 'letra', 'turno', 'modalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('seccion', 'detalle_malla')},
        ),
        migrations.AddIndex(
            model_name='componenteevaluacion',
            index=models.Index(fields=['curso', 'denominacion_periodo'], name='idx_comp_curso_periodo'),
        ),
        migrations.AddConstraint(
            model_name='componenteevaluacion',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gt', 0), ('peso__lte', 100)), name='ck_peso_rango_valido'),
        ),
        migrations.AlterUniqueTogether(
            name='componenteevaluacion',
            unique_together={('curso', 'denominacion_periodo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluacion', 'matricula')},
        ),
    ]
