# Generated by Django 5.2.6 on 2025-09-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiUgel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='AreaCurricular',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='CursoDocente',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='EntregaArchivo',
        ),
        migrations.DeleteModel(
            name='EstadoAsistencia',
        ),
        migrations.DeleteModel(
            name='EstadoCurso',
        ),
        migrations.DeleteModel(
            name='EstadoEntrega',
        ),
        migrations.DeleteModel(
            name='EstadoMatricula',
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='InstitucionEducativa',
        ),
        migrations.DeleteModel(
            name='MatriculaSeccion',
        ),
        migrations.DeleteModel(
            name='NivelEducativo',
        ),
        migrations.DeleteModel(
            name='PeriodoLectivo',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TareaArchivo',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='Ugel',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.DeleteModel(
            name='UsuarioRolInstitucion',
        ),
        migrations.DeleteModel(
            name='UsuarioRolUgel',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
